import {
  AlertCircle,
  AlertTriangle,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Copy,
  CopyCheck,
  Eye,
  EyeOff,
  Info,
  Loader2,
  Moon,
  Plus,
  RefreshCw,
  Search,
  Sun,
  Trash2,
  X,
  WifiOff,
  FolderOpen,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  spinner: Loader2,
  search: Search,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  checkCircle: CheckCircle2,
  info: Info,
  warning: AlertTriangle,
  error: AlertCircle,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  plus: Plus,
  trash: Trash2,
  copy: Copy,
  copyCheck: CopyCheck,
  sun: Sun,
  moon: Moon,
  refresh: RefreshCw,
  wifiOff: WifiOff,
  folderOpen: FolderOpen,
};
